### ISSUE TITLE
Issues with special character

### ISSUE THREAD

**Issue by sumanalapati** [thevictor13/angular-translate-csv#1]
This is not working with special characters.

Si cette option est sélectionnée, les symboles monétaires ne seront pas téléchargés ou imprimés. produced --> Si cette option est s�lectionn�e, les symboles mon�taires ne seront pas t�l�charg�s ou imprim�s.

Config
{
    "csvFileIn": "translations/a.csv",
    "jsonDirOut": "src/assets/i18n",
    "jsonFileName": "translations",
    "jsonExt": "json",
    "jsonIgnoreEmptyString": true,
    "jsonReplace": { "''": "\"" },
    "csvFieldSeparator": "\t",
    "csvEol": "\n",
    "csvEolAlt": ["\r\n", "\r"]
}

**Comment by dfjs** [comment]
@sumanalapati looking at the docs it seems unlikely that character support is an `angular-translate-csv` issue - might be worth checking your setup again for character encoding issues, etc
